data    = datatype.h
std     = ukr-std.h
string  = ukr-string.h
syntax  = syntax.h
ctime   = ukr-ctime.h
map     = ukr-map.h
vector  = ukr-vector.h
alg     = ukr-algorithm.h
list    = ukr-list.h
memory  = ukr-memory.h

start: data, std, syntax
	g++ file.cpp -0 start
